name: package-version-semver
description: set "semver" output from commit diff of package.json/lerna.json.
author: azu
branding:
  icon: file
  color: purple
runs:
  using: node12
  main: dist/index.js
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  package_version_filename:
    description: >
      Path to package json file like package.json or lerna.json.
      The package file should have version property.
      Default is package.json.
    required: false
    default: package.json
outputs:
  semver:
    description: >
      Semver type that is one of 'major' | 'premajor' | 'minor' | 'preminor' | 'patch' | 'prepatch' | 'prerelease'
