name: PR Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: |
          yarn install && yarn all
      - id: semver
        name: Run the action
        uses: ./
      - name: Print steps context output
        if: steps.semver.outputs.semver != ''
        run: |
          echo 'steps.semver.outputs.semver=${{ steps.semver.outputs.semver }}'
      - name: Print No semver
        if: steps.semver.outputs.semver == ''
        run: |
          echo 'No update'
      - name: Semver Label
        if: steps.semver.outputs.semver != ''
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: "Semver: ${{steps.semver.outputs.semver}}"
          type: add
      - name: Remove No Update Label
        if: steps.semver.outputs.semver != ''
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: "Semver: No Update"
          type: remove
      - name: Add No Update Label
        if: steps.semver.outputs.semver == ''
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: "Semver: No Update"
          type: add
