name: PR Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: |
          yarn install && yarn all
      - id: semver
        name: Run the action
        uses: ./
      - name: Print steps context output
        if: steps.semver.outputs.semver != ''
        run: |
          echo 'steps.semver.outputs.semver=${{ steps.semver.outputs.semver }}'
      - name: Print No semver
        if: steps.semver.outputs.semver == ''
        run: |
          echo 'No update'
      - name: Add Semver Label
        if: steps.semver.outputs.semver != ''
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Semver: ${{steps.semver.outputs.semver}}']
            });
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Semver: No Update'
            }).catch(error => {})
      - name: Add No Update Label
        if: steps.semver.outputs.semver == ''
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Semver: No Update']
            });
